version: '3'
services:
  sslauthapp:
    build: ./ssl-proxy
    ports: 
      - "443:443"
    depends_on: 
      - gateway
  gateway:
    build: ./src/linkapp.gateway
    ports:
     - "9090:8000"
    environment:
     - "LINKAPP_REDIS_URL=redis://redis:6379/0"
     - "LINKAPP_RABBIT_URL=amqp://rabbitmq:5672"
     - "LINKAPP_AUTHORIZATION_SERVICE_URL=http://gateway:12345@authapp:8000"
     - "LINKAPP_LINK_SERVICE_URL=http://linkapp:8000"
     - "LINKAPP_READINGLIST_SERVICE_URL=http://readinglistapp:8000"
     - "LINKAPP_TAG_SERVICE_URL=http://tagapp:8000"
    depends_on:
     - rabbitmq
     - redis
     - linkapp
     - authapp
     - tagapp
     - readinglistapp
  linkapp:
    build: ./src/linkapp.link
    ports:
     - "8000:8000"
    environment:
     - "LINKAPP_REDIS_URL=redis://redis:6379/0"
     - "LINKAPP_RABBIT_URL=amqp://rabbitmq:5672"
    depends_on:
     - rabbitmq
     - redis
  tagapp:
    build: ./src/linkapp.tag
    ports:
     - "8001:8000"
    environment:
     - "LINKAPP_REDIS_URL=redis://redis:6379/0"
     - "LINKAPP_RABBIT_URL=amqp://rabbitmq:5672"
    depends_on:
     - rabbitmq
     - redis
  authapp:
    build: ./src/linkapp.authentication
    ports:
     - "8002:8000"
    environment:
     - "LINKAPP_REDIS_URL=redis://redis:6379/0"
     - "LINKAPP_RABBIT_URL=amqp://rabbitmq:5672"
    depends_on:
     - rabbitmq
     - redis
  readinglistapp:
    build: ./src/linkapp.readinglist
    ports:
     - "8003:8000"
    environment:
     - "LINKAPP_REDIS_URL=redis://redis:6379/0"
     - "LINKAPP_RABBIT_URL=amqp://rabbitmq:5672"
    depends_on:
     - rabbitmq
     - redis
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
     - "5671:5671"
     - "5672:5672"
     - "8080:15672"