DOCKER_HOST=127.0.0.1
export LINKAPP_REDIS_URL="redis://$DOCKER_HOST:6379/0"
export LINKAPP_RABBIT_URL="amqp://$DOCKER_HOST:5672"
export LINKAPP_LINK_SERVICE_URL="http://$DOCKER_HOST:8000"
export LINKAPP_TAG_SERVICE_URL="http://$DOCKER_HOST:8001"
export LINKAPP_AUTHORIZATION_SERVICE_URL="http://$DOCKER_HOST:8002"
export LINKAPP_READINGLIST_SERVICE_URL="http://$DOCKER_HOST:8003"